networks:
  traefik_proxy:
    external: true

services:
  samba:
    image: dperson/samba:aarch64
    container_name: samba
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    volumes:
      - /piper:/piper
    command: '-u "zito;zito" -s "piper;/piper;yes;no;no;zito"'
