services:
  homeassistant:
    image: homeassistant/home-assistant:2025.3
    container_name: homeassistant
    restart: unless-stopped
    networks:
      home_network:
        ipv4_address: 192.168.1.3
      #domotic:
    volumes:
      - /piper/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      #- /run/dbus:/run/dbus:ro

networks:
  home_network:
    external: true
  #domotic:
