networks:
  traefik_proxy:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:10
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - traefik_proxy
    user: 1000:1000
    volumes:
      - /piper/jellyfin/config:/config
      - /piper/jellyfin/cache:/cache
      - /piper/jellyfin/media:/media:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=home_websecure"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.home.e-firmino.com`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
