services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - UI_TRAFFIC_STATS=true
      - WG_HOST=wireguard.e-firmino.com
      - WG_PORT=51820
      #- WG_MTU=1420
      #- WG_DEVICE=eth0
      #- WG_PERSISTENT_KEEPALIVE=30
      #- WG_DEFAULT_DNS=192.168.1.1
      #- WG_DEFAULT_ADDRESS=54.54.54.x
      #- WG_ALLOWED_IPS=0.0.0.0/0
    volumes:
      - /piper/wireguard/config:/etc/wireguard
      - /lib/modules:/lib/modules:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
      #- net.ipv6.conf.all.forwarding=1
      #- net.ipv6.conf.default.forwarding=1
    labels:
      - "traefik.enable=true"
      - "traefik.udp.routers.wireguard.entrypoints=wireguard"
      - "traefik.udp.services.wireguard.loadbalancer.server.port=51820"
      - "traefik.http.routers.wireguardWebUi.entrypoints=home_websecure"
      - "traefik.http.routers.wireguardWebUi.rule=Host(`wireguard.home.e-firmino.com`)"
      - "traefik.http.services.wireguardWebUi.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
